source /home/fortunate/my-localhost/Data/apps/black001.zsh
source /home/fortunate/my-localhost/Data/apps/brickstesting.zsh
source /home/fortunate/my-localhost/Data/apps/divitest.zsh
source /home/fortunate/my-localhost/Data/apps/python001.zsh
source /home/fortunate/my-localhost/Data/apps/python002.zsh
source /home/fortunate/my-localhost/Data/apps/pythondesktop01.zsh
source /home/fortunate/my-localhost/Data/apps/pythondesktop02.zsh
source /home/fortunate/my-localhost/Data/apps/pythondesktop03.zsh
source /home/fortunate/my-localhost/Data/apps/spraggoshopbricks.zsh
source /home/fortunate/my-localhost/Data/apps/spraggoshop.zsh
